all: base workstlr thrdpool

base:
	$(MAKE) -C base

workstlr:
	$(MAKE) -C workstlr

thrdpool:
	$(MAKE) -C thrdpool

clean:
	$(MAKE) -C base clean
	$(MAKE) -C workstlr clean
	$(MAKE) -C thrdpool clean

.PHONY: all base workstlr thrdpool clean
